### ISSUE TITLE
Advanced config section - Relaying with self-signed certs

### ISSUE THREAD

**Issue by cmsirbu** [mail-in-a-box/mailinabox.email#17]
When using self-signed certs, configuring another machine to use mailinabox for relaying fails because the certificate is untrusted.

There should be a Step 5 to take the cert from the mailinabox machine and add it to the trusted repo on the remote machine.

Can submit a PR if you think it's useful.

**Comment by JoshData** [comment]
Sure that'd be great. Just be sure to explain that it's only necessary with a self-signed cert. Once I'm able to integrate letsencrypt this might not be necessary as proper certs will be issued automatically.

**Comment by dhpiggott** [comment]
Yep, an unstated presumption of the current relaying instructions is that the mailinabox is not using a self-signed cert. It'd be great if you can improve them to accommodate this case as Josh has described!

FWIW, and in-case it's of interest to you: If you've taken the necessary steps with the mailinabox to enable DNSSEC, an alternative solution for establishing the mailinabox's identity would be to just set `smtp_tls_security_level` to [`dane-only`](http://www.postfix.org/TLS_README.html#client_tls_dane). You then don't need to install the mailinabox's certificate on the relay machine nor set `smtp_tls_CAfile`. However, you do have to configure the relay with a DNSSEC-enabled resolver.

**Comment by cmsirbu** [comment]
Letsencrypt can't come too soon really. Will be amazing when it's seamlessly integrated into mailinabox.

Thanks for the tip about DNSSEC @dhpiggott, will look into it. I won't add the instructions myself as I haven't tested them (no DNSSEC in my setup for now). There may be a point where it's not feasible to add all possible advanced deployment scenarios, although this is quite cool I have to say.

@JoshData have you thought about converting the guides to Markdown source and using something like gitbook or a simple template engine to generate the HTML for the site? I know it may look like too much work for a few pages, but I can help with that (generating my own site with pelican) and it will make contributing to documentation more accessible.

**Comment by JoshData** [comment]
@cmsirbu We could do that, but I don't really have time to make that change.
