### ISSUE TITLE
Move "mailinabox.email" to GitHub Pages

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox.email#30]
I think we should move "mailinabox.email" to GitHub Pages for security reasons.

**Comment by jeffreyalles** [comment]
What security issues do you have with Josh hosting it?

**Comment by aspdye** [comment]
What, if @JoshData gets hacked? It is (more) unlikely that GitHub gets hacked in a way, that the Pages are falsified or down in general.

**Comment by jeffreyalles** [comment]
In that same vein, someone could compromise an SSH key and change the repo. The website as is scan also be compared to the repo to see if there are any unauthorized modifications to the live page. Both Pages and the MIAB site use TLS, so there's a very, very small likelihood of MITM attacks. Moreover, it's arguably more likely someone would target the MIAB repo itself or the servers running MIAB than the website.

**Comment by JoshData** [comment]
Please don't open issues for hypothetical security problems. Describe a particular attack vector if you're concerned about something.
