### ISSUE TITLE
glue records with secondary DNS guide has been removed

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox.email#52]
_Originally posted by @steadfasterX in https://github.com/mail-in-a-box/mailinabox.email/commit/50ebc62b5c3922f8b53ad351564af253cf9ef803#commitcomment-30955134_

**Comment by alento-group** [comment]
Immediately before the link that needs to be removed there is a very minor typo....

>  That won’t work for Mail-in-a-Box’s typical setup since your machine will only have on IP address.

should be:

 That won’t work for Mail-in-a-Box’s typical setup since your machine will only have one IP address. 

I didn't create a pull request, as there will be another pull request created to remove the link (if the material cannot be found or recreated).

If you want me to create a pull request for this (these) let me know.

**Comment by JoshData** [comment]
I don't know/remember where that link came from, so I don't have any thoughts about it off hand. I'd be glad to merge a PR that fixes the typo and removes the link.

**Comment by alento-group** [comment]
I am working to write a replacement for that missing guide... not sure how quickly I will get it done though.  @JoshData I will want to ask your permission to use a couple of images from your original guide.  Basically, the two where you show the nameserver and glue record set ups with Gandi.  How should I proceed?

**Comment by alento-group** [comment]
@JoshData  - a proposed replacement guide is located at https://www.miabdnstest.ml/Secondary%20DNS%20for%20MiaB-5.html
It needs some cleaning up and also your permission to edit and use your images from the Set Up Guide.

**Comment by alento-group** [comment]
I have created a new guide and a pull request to incorporate it into the site.  It appears the pull request was merged ... what has to be done to publish the changes as the site is still unchanged?
@JoshData 
https://github.com/mail-in-a-box/mailinabox.email/pull/68

**Comment by JoshData** [comment]
For others reading (since we discussed on slack), I update the site manually after PRs are merged, and I've updated it now. :)
