### ISSUE TITLE
S3 Host / Endpoint not shown when using a custom service

### ISSUE THREAD

**Issue by severo** [mail-in-a-box/mailinabox.email#78]
I use the Scaleway S3 service, which is compatible with Amazon S3 protocol (everything works as expected), but there is a small bug.

I configured the host that way:

![Capture d’écran de 2020-12-21 14-04-42](https://user-images.githubusercontent.com/1676121/102790883-73b7f580-43a6-11eb-9d19-226701a61050.png)

But when I come back to the backup configuration page, the field is empty, while I expected to see it filled with `s3.fr-par.scw.cloud`:

![Capture d’écran de 2020-12-21 14-04-47](https://user-images.githubusercontent.com/1676121/102790885-74e92280-43a6-11eb-8907-c22b192e10da.png)

**Comment by myfirstnameispaul** [comment]
@severo This GitHub repository is for the [mailinabox.email](https://mailinabox.email) website. For issues related to the code of Mail-in-a-Box, see the [project GitHub](https://github.com/mail-in-a-box/mailinabox). For help with installation, first try the [forums](https://discourse.mailinabox.email)

**Comment by severo** [comment]
Oh, thanks for notifying. Moved to https://github.com/mail-in-a-box/mailinabox/issues/1980.
