### ISSUE TITLE
Issues adding certbot and duplicity PPAs

### ISSUE THREAD

**Issue by LogoiLab** [mail-in-a-box/mailinabox.email#80]
The install script hangs while installing the certbot and duplicity PPAs. Adding them manually remedies the issue and the installation can continue when rerun. Perhaps a permissions/script block/user interaction issue. PPAs require the user to hit ENTER to properly install.

**Comment by myfirstnameispaul** [comment]
@LogoiLab This GitHub is for the [mailinabox.email](https://mailinabox.email) website. For issues related to the code of Mail-in-a-Box, see the [project GitHub](https://github.com/mail-in-a-box/mailinabox). For help with installation, first try the [forums](https://discourse.mailinabox.email).

**Comment by LogoiLab** [comment]
It seems the issue may have been resolved on the main repo already, since this is on the wrong repo, going to go ahead and close this.
